### ISSUE TITLE
Outdated modules that contain vulnerabilities

### ISSUE THREAD

**Issue by izhakjakov** [grokify/go-aha#1]
`github.com/grokify/oauth2more@v0.4.0` uses `github.com/dgrijalva/jwt-go` which is affected by [a known vulnerability](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515) so it should probably be upgraded to `https://github.com/grokify/goauth@v0.10.4` which already resolved [this issue](https://github.com/grokify/goauth/issues/3)

Also updating other modules while working on this.

**Comment by izhakjakov** [comment]
I upgraded the modules on [my branch](https://github.com/izhakjakov/go-aha) but there are still modules that import the vulnerable `jwt` module via other modules.  
#### Here is the chain of imports:
```
〉ggdh 'github.com/dgrijalva/jwt-go@v3.2.0+incompatible'
             github.com/grokify/go-aha
                        ⬇
       github.com/grokify/googleutil@v0.1.0
                        ⬇
         github.com/grokify/goauth@v0.10.3
                        ⬇
        github.com/grokify/gocharts@v1.16.3
                        ⬇
       github.com/blend/go-sdk@v1.20211204.3
                        ⬇
           github.com/spf13/cobra@v1.1.1
                        ⬇
           github.com/spf13/viper@v1.7.0
                        ⬇
  github.com/dgrijalva/jwt-go@v3.2.0+incompatible
```
  
The problem is actually fixed in latest `github.com/spf13/cobra` but not in the latest `github.com/blend/go-sdk` so I will wait before upgrading it.
After it get fixed I can go ahead and update all the imports in dependency chain.

**Comment by izhakjakov** [comment]
Fixed in blend/go-sdk#248

There are other modules that could be upgrade.  
Please lmk if you want me to do so.

**Comment by grokify** [comment]
Modules have been updated. `github.com/dgrijalva/jwt-go` is still in `go.sum` but the Dependabot is gone now.

**Comment by izhakjakov** [comment]
Thank you Grokify 🙏   
I am waiting for [my change to github.com/blend/go-sdk](https://github.com/blend/go-sdk/pull/248) to be merged then I can help you update the dependency chain for the rest of your modules.

**Comment by grokify** [comment]
Sounds good. Thanks @izhakjakov. I'll look for the PR.

In the mean while, I've released [v0.2.3](https://github.com/grokify/go-aha/releases/tag/v0.2.3) to reduce some more direct dependencies in my modules.

**Comment by izhakjakov** [comment]
Thank you for LMK

**Comment by izhakjakov** [comment]
## I found more vulnerabilities:

### [SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825)
```
〉ggdh 'github.com/miekg/dns'
                     github.com/grokify/go-aha
                                ⬇
                github.com/grokify/gocharts@v1.16.8
                                ⬇
               github.com/blend/go-sdk@v1.20211204.3
                                ⬇
                   github.com/spf13/cobra@v1.1.1
                                ⬇
                   github.com/spf13/viper@v1.7.0
                                ⬇
  github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c
                                ⬇
              github.com/hashicorp/consul/api@v1.1.0
                                ⬇
                 github.com/hashicorp/serf@v0.8.2
                                ⬇
                 github.com/hashicorp/mdns@v1.0.0
                                ⬇
                   github.com/miekg/dns@v1.0.14
```
[My change to github.com/blend/go-sdk](https://github.com/blend/go-sdk/pull/248) should fix that as well.

### [SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251)
All the vulnerable deps are again inherited from [github.com/blend/go-sdk](https://github.com/blend/go-sdk) (v1.20211204.3 to be exact), however, this time my change won't fix it and a more complicate change is needed so I will open an issue in their repo.


### [SNYK-GOLANG-GITHUBCOMCLOUDFLAREGOLZ4-50050](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCLOUDFLAREGOLZ4-50050)
```
〉ggdh 'github.com/cloudflare/golz4'
                    github.com/grokify/go-aha
                                ⬇
                github.com/grokify/goauth@v0.10.6
                                ⬇
                 github.com/astaxie/beego@v1.12.3
                                ⬇
  github.com/cloudflare/golz4@v0.0.0-20150217214814-ef862a3cdc58
```
Fix is currently only in [github.com/astaxie/beego in beta release](https://github.com/astaxie/beego/tree/v2.0.0-beta).

**Comment by grokify** [comment]
Thanks for the update.

The following is an indirect dependency. Can you identify the direct dependency chain from `gocharts` to `blend/go-sdk`?

```
                github.com/grokify/gocharts@v1.16.8
                                ⬇
               github.com/blend/go-sdk@v1.20211204.3
```

**Comment by izhakjakov** [comment]
Yes I know that's why I made [a change in their repo](https://github.com/blend/go-sdk/pull/248)
I am also opening an issue (in their repo) now for [SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251)

**Comment by grokify** [comment]
> Yes I know that's why I made [a change in their repo](https://github.com/blend/go-sdk/pull/248) I am also opening an issue (in their repo) now for [SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251)

`github.com/jackc/pgproto3/v2` also isn't a direct dependency.

Are you able to identify which direct dependency is pulling these in?

**Comment by izhakjakov** [comment]
> How are you identifying these issues? I'd like to find these as well!

I don't find the issues.  They get assigned to me.
The dependency report is created by [a script that I wrote](https://github.com/izhakjakov/getGoDependencyHierarchy/blob/main/getGoDependencyHierarchy).

**Comment by izhakjakov** [comment]
> I am also opening an issue (in their repo) now for SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251

Opened [an issue](https://github.com/blend/go-sdk/issues/249) and submitted a fix.

**Comment by grokify** [comment]
[SNYK-GOLANG-GITHUBCOMCLOUDFLAREGOLZ4-50050](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCLOUDFLAREGOLZ4-50050) has been resolved by removing `github.com/cloudflare/golz4@v0.0.0-20150217214814-ef862a3cdc58` as an indirect dependency.

**Comment by grokify** [comment]
Continuing to track open items:

1. [SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825) - `github.com/miekg/dns@v1.0.14` - to be resolved in https://github.com/blend/go-sdk/pull/248
1. [SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-1316251) - `github.com/jackc/pgproto3/v2`

**Comment by grokify** [comment]
@izhakjakov Looks like your PR was closed:

https://github.com/blend/go-sdk/pull/248

But the following vulnerable dependencies still remain

1. github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
1. github.com/jackc/pgproto3/v2 v2.0.0-alpha1.0.20190420180111-c116219b62db/go.mod h1:bhq50y+xrl9n5mRYyCBFKkpRVTLYJVWeCc+mEAI3yXA=
1. github.com/jackc/pgproto3/v2 v2.0.0-alpha1.0.20190609003834-432c2951c711/go.mod h1:uH0AWtUmuShn0bcesswc4aBTWGvw0cAxIJp+6OB//Wg=
1. github.com/jackc/pgproto3/v2 v2.0.0-rc3/go.mod h1:ryONWYqW6dqSg1Lw6vXNMXoBJhpzvWKnT95C46ckYeM=
1. github.com/jackc/pgproto3/v2 v2.0.0-rc3.0.20190831210041-4c03ce451f29/go.mod h1:ryONWYqW6dqSg1Lw6vXNMXoBJhpzvWKnT95C46ckYeM=
1. github.com/jackc/pgproto3/v2 v2.0.6/go.mod h1:WfJCnwN3HIg9Ish/j3sgWXnAfK8A9Y0bwXYU5xKaEdA=
1. github.com/miekg/dns v1.0.14/go.mod h1:W1PPwlIAgtquWBMBEV9nkV9Cazfe8ScdGz/Lj7v3Nrg=

**Comment by grokify** [comment]
To resolve this issue, I removed `github.com/blend/go-sdk` in `v0.2.5`.

The following identified vulnerable modules are no longer dependencies, along with many other eliminated modules.

1. github.com/cloudflare/golz4
1. github.com/dgrijalva/jwt-go
1. github.com/jackc/pgproto3/v2
1. github.com/miekg/dns

Please verify and let me know if anything else is open.

**Comment by grokify** [comment]
@izhakjakov I'm closing this now, but I did post in the PR that the issues are still open in `github.com/blend/go-sdk` here:

https://github.com/blend/go-sdk/pull/248

Please post if anything else comes up and thanks for reporting this!

**Comment by grokify** [comment]
> Not everything but yes you should close since there isn't much we can do, [blend/go-sdk](https://github.com/blend/go-sdk) don't accept commits from outsiders.

Everything with respect to this project, as [blend/go-sdk](https://github.com/blend/go-sdk) is no longer a dependency.

It was good go upgrade [github.com/wcharczuk/go-chart](https://github.com/wcharczuk/go-chart) to remove it.

It seems like your script didn't track the dependency chain to  [github.com/wcharczuk/go-chart](https://github.com/wcharczuk/go-chart), and could possibly be enhanced.

You reported:

```
        github.com/grokify/gocharts@v1.16.3
                        ⬇
       github.com/blend/go-sdk@v1.20211204.3
```

but this was missing `github.comwcharczuk/go-chart`. The dependency chain between the two was the following, which I tracked down manually.

```
        github.com/grokify/gocharts@v1.16.3
                        ⬇
 github.com/wcharczuk/go-chart v2.0.1+incompatible
                        ⬇
       github.com/blend/go-sdk@v1.20211204.3
```

Here's the full `go.mod` for [github.com/grokify/gocharts@v1.16.3](https://github.com/grokify/gocharts/tree/v1.16.3).

https://github.com/grokify/gocharts/blob/v1.16.3/go.mod

```
module github.com/grokify/gocharts

go 1.16

require (
	github.com/360EntSecGroup-Skylar/excelize v1.4.1
	github.com/blend/go-sdk v1.20211204.3 // indirect
	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0 // indirect
	github.com/grokify/elastirad-go v0.1.4
	github.com/grokify/mogo v0.32.3
	github.com/jessevdk/go-flags v1.5.0
	github.com/mattn/go-runewidth v0.0.13 // indirect
	github.com/olekukonko/tablewriter v0.0.5
	github.com/pkg/errors v0.9.1
	github.com/valyala/quicktemplate v1.7.0
	github.com/wcharczuk/go-chart v2.0.1+incompatible
	golang.org/x/sys v0.0.0-20211210111614-af8b64212486 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)
```

**Comment by izhakjakov** [comment]
Oh nice, I think no `blend/go-sdk` is a good idea :)
  
I am not why my script is not detecting this but can try to investigate tomorrow.
My script is not perfect unfortunately and relies on `go mod graph` which isn't perfect either :/

**Comment by izhakjakov** [comment]
Looks like the reason `github.com/wcharczuk/go-chart v2.0.1+incompatible` was left out by my script is because it does not have `go.mod`&`go.sum`.  
In order to not contaminate this issue, would you mind opening an issue (nothing fancy) on [the script's repo](https://github.com/izhakjakov/getGoDependencyHierarchy/blob/main/getGoDependencyHierarchy) and explain how you found this dep manually?

**Comment by grokify** [comment]
> Looks like the reason `github.com/wcharczuk/go-chart v2.0.1+incompatible` was left out by my script is because it does not have `go.mod`&`go.sum`.

Agreed. A module indicated as *incompatible* means it's not managed under Go modules and has no `go.mod` file.

> In order to not contaminate this issue, would you mind opening an issue (nothing fancy) on [the script's repo](https://github.com/izhakjakov/getGoDependencyHierarchy) and explain how you found this dep manually?

Done! :+1:
