### ISSUE TITLE
Newest release is ignored by "go mod tidy"

### ISSUE THREAD

**Issue by izhakjakov** [grokify/go-aha#2]
## Newest release is ignored by `go mod tidy`
For some reason `go mod tidy` does not pick up the newest release (currently `v0.2.6` from 13/01/2022)  
  
It always picks up `v1.0.0` from 30/10/2020 or `v2.3.0+incompatible` from 19/12/2017
  
<img src='https://user-images.githubusercontent.com/18270061/149964295-04fb661d-7b21-4448-bc7b-6689920379ef.png' width='50%' height='50%'>
<a href="https://pkg.go.dev/github.com/grokify/go-aha?tab=versions" rel="nofollow"><sup>pkg.go.dev/github.com/grokify/go-aha</sup></a>

**Comment by grokify** [comment]
@izhakjakov That was a hold over from some failed experiments to learn about how Go Modules does versioning.

I've upgraded this to [v2.4.0](https://github.com/grokify/go-aha/releases/tag/v2.4.0) which should be higher than all the listed versions.

This now needs to be required as:

`github.com/grokify/go-aha/v2`

**Comment by izhakjakov** [comment]
Thank you
