### ISSUE TITLE
Please update go.mod for fast http.

### ISSUE THREAD

**Issue by hvetsa** [grokify/go-aha#3]
WE are using the latest go-aha @2.4.0 version.

It is dependent on fast http 1.32.0

Our vulnerability scan indicates that fast http 1.32.0 is vulnerable and should use 1.34.0.

Any help is greatly appreciated.

**Comment by grokify** [comment]
Fixed in [v2.4.1](https://github.com/grokify/go-aha/releases/tag/v2.4.1).

**Comment by grokify** [comment]
FYI. Dependabot has been added to do a daily check for upgradeable dependencies so hopefully this will be caught earlier if it happens with a dependency again.

https://github.com/grokify/go-aha/blob/master/.github/dependabot.yaml
